server:
  port: 9527

spring:
  application:
    name: springcloud-gateway
  cloud:
    gateway:
      routes:
        - id: routh1
          uri: http://localhost:8001
          preicates:
            - Path=/dept/queryAll

        - id: routh2
            uri: http://localhost:8001
            preicates:
              - Path=/dept/query/**


eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka
  instance:
    instance-id: gateway9527.com
    prefer-ip-address: true

info:
  app.name: duming-springcloud
  company.name: dumingstudy.com
