server:
  port: 3344
spring:
  application:
    name: springcloud-config-server
    #链接远程仓库
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/dumingstudy/springcloud-config.git #是https，不是ssh

#通过config-server，可以连接到git，访问其中的资源以及配置